### ISSUE TITLE
[fuzzing] spec-actors@0.9.3/actors/crypto.(*Signature).UnmarshalCBOR panic

### ISSUE THREAD

**Issue by bryanchriswhite** [LeastAuthority/lotus#2]
# Context
Crashing inputs were discovered while fuzzing lotu's types.DecodeBlockMsg function. At least one of these traces back to specs-actors (at v0.9.3: [UnmarshalCBOR](https://github.com/filecoin-project/specs-actors/blob/v0.9.3/actors/crypto/signature.go#L83)) as you can see in the example below.

# Crasher
```
5768b489b05e7e500297864bebfa033722c98680
```

## Quoted input
```
        "\x83\x90C\x00\xda0\xf6\x82:0000@\x80\x80\x80Q\x000" +
        "000000000000000;0000" +
        "0000\xd8*K\x00\x0100\x06000000\xd8*" +
        "K\x00\x0100\x06000000\xd8*K\x00\x010\xf6\x81" +
        "0\x040000@"
```

## Output
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/filecoin-project/specs-actors/actors/crypto.(*Signature).UnmarshalCBOR(0xc000277500, 0xe1f240, 0xc0001bb650, 0xe1f240, 0xc0001bb650)
        /go/pkg/mod/github.com/filecoin-project/specs-actors@v0.9.3/actors/crypto/signature.go:83 +0x472
github.com/filecoin-project/lotus/chain/types.(*BlockHeader).UnmarshalCBOR(0xc00027e380, 0xe1f240, 0xc0001bb650, 0xe1f240, 0xc0001bb650)
        /go/pkg/mod/github.com/filecoin-project/lotus@v0.5.10/chain/types/cbor_gen.go:386 +0x1d9e
github.com/filecoin-project/lotus/chain/types.(*BlockMsg).UnmarshalCBOR(0xc00007cf00, 0xe1f240, 0xc0001bb650, 0xc000175e88, 0x48d8ee)
        /go/pkg/mod/github.com/filecoin-project/lotus@v0.5.10/chain/types/cbor_gen.go:1325 +0xd8f
github.com/filecoin-project/lotus/chain/types.DecodeBlockMsg(0x7f867d9a1000, 0x57, 0x57, 0x2e0485a0, 0x2e0485a000000000, 0x5f60fb0b)
        /go/pkg/mod/github.com/filecoin-project/lotus@v0.5.10/chain/types/blockmsg.go:17 +0xd6
github.com/filecoin-project/fuzzing-lotus/fuzz.FuzzBlockMsg(0x7f867d9a1000, 0x57, 0x57, 0x4)
        /tmp/fuzzing/fuzz/fuzz.go:15 +0x59
go-fuzz-dep.Main(0xc000175f60, 0x3, 0x3)
        go-fuzz-dep/main.go:36 +0x1ad
main.main()
        github.com/filecoin-project/fuzzing-lotus/fuzz/go.fuzz.main/main.go:19 +0x72

goroutine 6 [select]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc0001ba360)
        /go/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:71 +0x158
created by github.com/ipfs/go-log/writer.NewMirrorWriter
        /go/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:36 +0xd1
```

**Comment by anorth** [comment]
Thanks. We found and fixed this independently a few weeks ago.

The fix was subtly included in https://github.com/filecoin-project/specs-actors/pull/1103, and then propagated when the file in question then moved to https://github.com/filecoin-project/go-state-types/pull/4.
